togglz:
  features:
    DISCOUNT_APPLIED:
      enabled: true
  features-file: 'file://home/sachin/Desktop/feature.properties'
  console:
    secured: false
management:
  endpoints:
    web:
      exposure:
        include: 'togglz'
